apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  
  labels:
    app: {{ .Values.app.name }}
type: Opaque
stringData:
  LNCR_OAUTH_ADMIN_CLIENT_ID: "{{ .Values.secrets.oauthAdminClientId }}"
  LNCR_OAUTH_ADMIN_CLIENT_SECRET: "{{ .Values.secrets.oauthAdminClientSecret }}"
  LNCR_OAUTH_MONITOR_CLIENT_ID: "{{ .Values.secrets.oauthMonitorClientId }}"
  LNCR_OAUTH_MONITOR_CLIENT_SECRET: "{{ .Values.secrets.oauthMonitorClientSecret }}"
  LNCR_OAUTH_TOTEM_CLIENT_ID: "{{ .Values.secrets.oauthTotemClientId}}"
  LNCR_OAUTH_TOTEM_CLIENT_SECRET: "{{ .Values.secrets.oauthTotemClientSecret}}"
  LNCR_OAUTH_SECRET_KEY: "{{ .Values.secrets.oauthSecretKey }}"
  MERCADOPAGO_CLIENT_ID: "{{ .Values.secrets.mercadopagoClientId }}"
  MERCADOPAGO_SECRET_ID: "{{ .Values.secrets.mercadopagoSecretId }}"
  MERCADOPAGO_POS_ID: "{{ .Values.secrets.mercadopagoPosId }}"
  POSTGRES_URL: "{{ .Values.secrets.postgresUrl }}"
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgresPassword }}"
  POSTGRES_USER: "{{ .Values.secrets.postgresUser }}"



