name: Print Secrets

on:
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Print All Secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CUSTOMER_EXTERNAL_URL: ${{ secrets.CUSTOMER_EXTERNAL_URL }}
          CUSTOMER_ORDER_POSTGRES_PASSWORD: ${{ secrets.CUSTOMER_ORDER_POSTGRES_PASSWORD }}
          CUSTOMER_ORDER_POSTGRES_URL: ${{ secrets.CUSTOMER_ORDER_POSTGRES_URL }}
          CUSTOMER_ORDER_POSTGRES_USER: ${{ secrets.CUSTOMER_ORDER_POSTGRES_USER }}
          FOOD_ITEM_EXTERNAL_URL: ${{ secrets.FOOD_ITEM_EXTERNAL_URL }}
          FOOD_ITEM_POSTGRES_PASSWORD: ${{ secrets.FOOD_ITEM_POSTGRES_PASSWORD }}
          FOOD_ITEM_POSTGRES_URL: ${{ secrets.FOOD_ITEM_POSTGRES_URL }}
          FOOD_ITEM_POSTGRES_USER: ${{ secrets.FOOD_ITEM_POSTGRES_USER }}
          KITCHEN_ORDER_POSTGRES_PASSWORD: ${{ secrets.KITCHEN_ORDER_POSTGRES_PASSWORD }}
          KITCHEN_ORDER_POSTGRES_URL: ${{ secrets.KITCHEN_ORDER_POSTGRES_URL }}
          KITCHEN_ORDER_POSTGRES_USER: ${{ secrets.KITCHEN_ORDER_POSTGRES_USER }}
          MERCADOPAGO_CLIENT_ID: ${{ secrets.MERCADOPAGO_CLIENT_ID }}
          MERCADOPAGO_EXPIRATION_TIME: ${{ secrets.MERCADOPAGO_EXPIRATION_TIME }}
          MERCADOPAGO_OAUTH_URL: ${{ secrets.MERCADOPAGO_OAUTH_URL }}
          MERCADOPAGO_ORDERS_URL: ${{ secrets.MERCADOPAGO_ORDERS_URL }}
          MERCADOPAGO_POS_ID: ${{ secrets.MERCADOPAGO_POS_ID }}
          MERCADOPAGO_SECRET_ID: ${{ secrets.MERCADOPAGO_SECRET_ID }}
          MERCADOPAGO_WEBHOOK_SECRET: ${{ secrets.MERCADOPAGO_WEBHOOK_SECRET }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NOTIFICATION_POSTGRES_PASSWORD: ${{ secrets.NOTIFICATION_POSTGRES_PASSWORD }}
          NOTIFICATION_POSTGRES_URL: ${{ secrets.NOTIFICATION_POSTGRES_URL }}
          NOTIFICATION_POSTGRES_USER: ${{ secrets.NOTIFICATION_POSTGRES_USER }}
          PAYMENT_POSTGRES_PASSWORD: ${{ secrets.PAYMENT_POSTGRES_PASSWORD }}
          PAYMENT_POSTGRES_URL: ${{ secrets.PAYMENT_POSTGRES_URL }}
          PAYMENT_POSTGRES_USER: ${{ secrets.PAYMENT_POSTGRES_USER }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
          echo "CUSTOMER_EXTERNAL_URL=$CUSTOMER_EXTERNAL_URL"
          echo "CUSTOMER_ORDER_POSTGRES_PASSWORD=$CUSTOMER_ORDER_POSTGRES_PASSWORD"
          echo "CUSTOMER_ORDER_POSTGRES_URL=$CUSTOMER_ORDER_POSTGRES_URL"
          echo "CUSTOMER_ORDER_POSTGRES_USER=$CUSTOMER_ORDER_POSTGRES_USER"
          echo "FOOD_ITEM_EXTERNAL_URL=$FOOD_ITEM_EXTERNAL_URL"
          echo "FOOD_ITEM_POSTGRES_PASSWORD=$FOOD_ITEM_POSTGRES_PASSWORD"
          echo "FOOD_ITEM_POSTGRES_URL=$FOOD_ITEM_POSTGRES_URL"
          echo "FOOD_ITEM_POSTGRES_USER=$FOOD_ITEM_POSTGRES_USER"
          echo "KITCHEN_ORDER_POSTGRES_PASSWORD=$KITCHEN_ORDER_POSTGRES_PASSWORD"
          echo "KITCHEN_ORDER_POSTGRES_URL=$KITCHEN_ORDER_POSTGRES_URL"
          echo "KITCHEN_ORDER_POSTGRES_USER=$KITCHEN_ORDER_POSTGRES_USER"
          echo "MERCADOPAGO_CLIENT_ID=$MERCADOPAGO_CLIENT_ID"
          echo "MERCADOPAGO_EXPIRATION_TIME=$MERCADOPAGO_EXPIRATION_TIME"
          echo "MERCADOPAGO_OAUTH_URL=$MERCADOPAGO_OAUTH_URL"
          echo "MERCADOPAGO_ORDERS_URL=$MERCADOPAGO_ORDERS_URL"
          echo "MERCADOPAGO_POS_ID=$MERCADOPAGO_POS_ID"
          echo "MERCADOPAGO_SECRET_ID=$MERCADOPAGO_SECRET_ID"
          echo "MERCADOPAGO_WEBHOOK_SECRET=$MERCADOPAGO_WEBHOOK_SECRET"
          echo "MONGODB_URI=$MONGODB_URI"
          echo "NOTIFICATION_POSTGRES_PASSWORD=$NOTIFICATION_POSTGRES_PASSWORD"
          echo "NOTIFICATION_POSTGRES_URL=$NOTIFICATION_POSTGRES_URL"
          echo "NOTIFICATION_POSTGRES_USER=$NOTIFICATION_POSTGRES_USER"
          echo "PAYMENT_POSTGRES_PASSWORD=$PAYMENT_POSTGRES_PASSWORD"
          echo "PAYMENT_POSTGRES_URL=$PAYMENT_POSTGRES_URL"
          echo "PAYMENT_POSTGRES_USER=$PAYMENT_POSTGRES_USER"
          echo "REPO_TOKEN=$REPO_TOKEN"
